//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class directories {
    
    private directoriesDirectory[] directoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("directory")]
    public directoriesDirectory[] directory {
        get {
            return this.directoryField;
        }
        set {
            this.directoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class directoriesDirectory {
    
    private directoriesDirectoryCounter counterField;
    
    /// <remarks/>
    public directoriesDirectoryCounter counter {
        get {
            return this.counterField;
        }
        set {
            this.counterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class directoriesDirectoryCounter {
    
    private string counternameField;
    
    private string uncdirectoryField;
    
    private string filterField;
    
    private directoriesDirectoryCounterType typeField;
    
    private directoriesDirectoryCounterSchedule scheduleField;
    
    /// <remarks/>
    public string countername {
        get {
            return this.counternameField;
        }
        set {
            this.counternameField = value;
        }
    }
    
    /// <remarks/>
    public string uncdirectory {
        get {
            return this.uncdirectoryField;
        }
        set {
            this.uncdirectoryField = value;
        }
    }
    
    /// <remarks/>
    public string filter {
        get {
            return this.filterField;
        }
        set {
            this.filterField = value;
        }
    }
    
    /// <remarks/>
    public directoriesDirectoryCounterType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public directoriesDirectoryCounterSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum directoriesDirectoryCounterType {
    
    /// <remarks/>
    count,
    
    /// <remarks/>
    size,
    
    /// <remarks/>
    lastmodified,
    
    /// <remarks/>
    oldest,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class directoriesDirectoryCounterSchedule {
    
    private string daypatternField;
    
    private System.DateTime startField;
    
    private System.DateTime endField;
    
    private directoriesDirectoryCounterScheduleFrequency frequencyField;
    
    private int everyField;
    
    /// <remarks/>
    public string daypattern {
        get {
            return this.daypatternField;
        }
        set {
            this.daypatternField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    public directoriesDirectoryCounterScheduleFrequency frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    public int every {
        get {
            return this.everyField;
        }
        set {
            this.everyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum directoriesDirectoryCounterScheduleFrequency {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    H,
}
