//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class services {
    
    private servicesService[] serviceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service")]
    public servicesService[] service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class servicesService {
    
    private string servicedescriptionField;
    
    private string machinenameField;
    
    private string servicenameField;
    
    private servicesServiceSchedule scheduleField;
    
    /// <remarks/>
    public string servicedescription {
        get {
            return this.servicedescriptionField;
        }
        set {
            this.servicedescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string machinename {
        get {
            return this.machinenameField;
        }
        set {
            this.machinenameField = value;
        }
    }
    
    /// <remarks/>
    public string servicename {
        get {
            return this.servicenameField;
        }
        set {
            this.servicenameField = value;
        }
    }
    
    /// <remarks/>
    public servicesServiceSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class servicesServiceSchedule {
    
    private string daypatternField;
    
    private System.DateTime startField;
    
    private System.DateTime endField;
    
    private servicesServiceScheduleFrequency frequencyField;
    
    private int everyField;
    
    /// <remarks/>
    public string daypattern {
        get {
            return this.daypatternField;
        }
        set {
            this.daypatternField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    public servicesServiceScheduleFrequency frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    public int every {
        get {
            return this.everyField;
        }
        set {
            this.everyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum servicesServiceScheduleFrequency {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    H,
}
