//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class eventlogs {
    
    private eventlogsEventlog[] eventlogField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("eventlog")]
    public eventlogsEventlog[] eventlog {
        get {
            return this.eventlogField;
        }
        set {
            this.eventlogField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eventlogsEventlog {
    
    private string nameField;
    
    private string descriptionField;
    
    private string eventlognameField;
    
    private string sourceField;
    
    private string machinenameField;
    
    private eventlogsEventlogLevel levelField;
    
    private string queryField;
    
    private eventlogsEventlogSchedule scheduleField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string eventlogname {
        get {
            return this.eventlognameField;
        }
        set {
            this.eventlognameField = value;
        }
    }
    
    /// <remarks/>
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string machinename {
        get {
            return this.machinenameField;
        }
        set {
            this.machinenameField = value;
        }
    }
    
    /// <remarks/>
    public eventlogsEventlogLevel level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public string query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    public eventlogsEventlogSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum eventlogsEventlogLevel {
    
    /// <remarks/>
    Information,
    
    /// <remarks/>
    Warning,
    
    /// <remarks/>
    Error,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eventlogsEventlogSchedule {
    
    private string daypatternField;
    
    private System.DateTime startField;
    
    private System.DateTime endField;
    
    private eventlogsEventlogScheduleFrequency frequencyField;
    
    private int everyField;
    
    /// <remarks/>
    public string daypattern {
        get {
            return this.daypatternField;
        }
        set {
            this.daypatternField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    public eventlogsEventlogScheduleFrequency frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    public int every {
        get {
            return this.everyField;
        }
        set {
            this.everyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum eventlogsEventlogScheduleFrequency {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    H,
}
