//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class databases {
    
    private databasesDatabase[] databaseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("database")]
    public databasesDatabase[] database {
        get {
            return this.databaseField;
        }
        set {
            this.databaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class databasesDatabase {
    
    private databasesDatabaseCounter counterField;
    
    /// <remarks/>
    public databasesDatabaseCounter counter {
        get {
            return this.counterField;
        }
        set {
            this.counterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class databasesDatabaseCounter {
    
    private string counternameField;
    
    private string connectionstringField;
    
    private string queryField;
    
    private databasesDatabaseCounterSchedule scheduleField;
    
    /// <remarks/>
    public string countername {
        get {
            return this.counternameField;
        }
        set {
            this.counternameField = value;
        }
    }
    
    /// <remarks/>
    public string connectionstring {
        get {
            return this.connectionstringField;
        }
        set {
            this.connectionstringField = value;
        }
    }
    
    /// <remarks/>
    public string query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    public databasesDatabaseCounterSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class databasesDatabaseCounterSchedule {
    
    private string daypatternField;
    
    private System.DateTime startField;
    
    private System.DateTime endField;
    
    private databasesDatabaseCounterScheduleFrequency frequencyField;
    
    private int everyField;
    
    /// <remarks/>
    public string daypattern {
        get {
            return this.daypatternField;
        }
        set {
            this.daypatternField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    public databasesDatabaseCounterScheduleFrequency frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    public int every {
        get {
            return this.everyField;
        }
        set {
            this.everyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum databasesDatabaseCounterScheduleFrequency {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    H,
}
