//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class perfcounters {
    
    private perfcountersPerfcounter[] perfcounterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("perfcounter")]
    public perfcountersPerfcounter[] perfcounter {
        get {
            return this.perfcounterField;
        }
        set {
            this.perfcounterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class perfcountersPerfcounter {
    
    private string nameField;
    
    private string categoryField;
    
    private string counternameField;
    
    private string instanceField;
    
    private perfcountersPerfcounterSchedule scheduleField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public string countername {
        get {
            return this.counternameField;
        }
        set {
            this.counternameField = value;
        }
    }
    
    /// <remarks/>
    public string instance {
        get {
            return this.instanceField;
        }
        set {
            this.instanceField = value;
        }
    }
    
    /// <remarks/>
    public perfcountersPerfcounterSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class perfcountersPerfcounterSchedule {
    
    private string daypatternField;
    
    private System.DateTime startField;
    
    private System.DateTime endField;
    
    private perfcountersPerfcounterScheduleFrequency frequencyField;
    
    private int everyField;
    
    /// <remarks/>
    public string daypattern {
        get {
            return this.daypatternField;
        }
        set {
            this.daypatternField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    public perfcountersPerfcounterScheduleFrequency frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    public int every {
        get {
            return this.everyField;
        }
        set {
            this.everyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum perfcountersPerfcounterScheduleFrequency {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    H,
}
